Update LayerTreeHost.h
I think this have a connection with the build failed because of disabling video. Below are the build arguments

CONFIGURE_ENV =		WK_USE_CCACHE=NO
CONFIGURE_ARGS =	-DPORT=GTK \
			-DENABLE_MINIBROWSER=ON \
			-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
			-DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}" \
			-DUSE_SYSTEMD=OFF

CONFIGURE_ARGS +=       -DCMAKE_BUILD_TYPE=Release
CONFIGURE_ARGS +=       -DUSE_LD_GOLD=OFF
CONFIGURE_ARGS +=       -DENABLE_OPENGL=OFF
CONFIGURE_ARGS +=       -DENABLE_GLES2=OFF
CONFIGURE_ARGS +=       -DUSE_GSTREAMER_GL=OFF
CONFIGURE_ARGS +=       -DUSE_OPENGL_OR_ES=OFF
CONFIGURE_ARGS +=       -DENABLE_WEBGL=OFF
CONFIGURE_ARGS +=       -DENABLE_WEB_AUDIO=OFF
CONFIGURE_ARGS +=       -DENABLE_VIDEO=OFF
CONFIGURE_ARGS +=       -DENABLE_MEDIA_SOURCE=OFF
CONFIGURE_ARGS +=       -DENABLE_SPELLCHECK=OFF
CONFIGURE_ARGS +=       -DUSE_LIBHYPHEN=OFF
CONFIGURE_ARGS +=       -DENABLE_GEOLOCATION=OFF
CONFIGURE_ARGS +=       -DENABLE_DRAG_SUPPORT=OFF
CONFIGURE_ARGS +=       -DENABLE_GAMEPAD=OFF
CONFIGURE_ARGS +=       -DUSE_LIBSECRET=OFF
CONFIGURE_ARGS +=       -DENABLE_CREDENTIAL_STORAGE=OFF
CONFIGURE_ARGS +=       -DENABLE_PLUGIN_PROCESS_GTK2=OFF

It will raise a build error near to the end of build:

In file included from DerivedSources/WebKit/unified-sources/UnifiedSource-54928a2b-35.cpp:8:
In file included from /_PORTS/pobj/webkitgtk4-2.34.1/webkitgtk-2.34.1/Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/DrawingAreaCoordinatedGraphics.cpp:32:
/_PORTS/pobj/webkitgtk4-2.34.1/webkitgtk-2.34.1/Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/LayerTreeHost.h:41:10: fatal error: 'WebCore/CoordinatedGraphicsLayer.h' file not found
#include <WebCore/CoordinatedGraphicsLayer.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.